RsMotores.WEB/Models/ErrorMessage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RsMotores.WEB.Models
{
    public class ErrorMessage
    {
        public string msg;
        
        /// <summary>
        /// Coloca uma mensagem de erro na variável msg 
        /// 1 - Erro de Login,
        /// 2 - Erro de Cpf, 
        /// 3 - Erro de Campos em branco;
        /// </summary>
        /// <param name="tipo"></param>
        public ErrorMessage(int tipo)
        {
            switch (tipo)
            {
                case 1:
                    msg = "Login inválido. Email e senha não encontrados!";
                    break;

                case 2:
                    msg = "Cpf inválido. O cpf informado está inválido!";
                    break;
                case 3:
                    msg = "Campos: Email e senha não podem ser vazios!";
                    break;
                default:
                    msg = "Erro não reconhecido. Entrar em contato com suporte admin@admin.";
                    break;
            }
        }
    }
}

RsMotores.WEB/Models/ErrorViewModel.cs
using System;

namespace RsMotores.WEB.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RsMotores.WEB/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RsMotores.WEB.Models
{
    public class Usuario
    {
        public int Id { get; set; }
        public string nome;
        public string cpf;
        public string email;
        public string password;

        public bool ValidaCpf(string dados)
        {
            var aux = dados.Replace(".", "");
            aux = dados.Replace("-", "");
            aux = dados.Replace(" ", "");
            //if (aux.Length == 11)
            //{
            //    return true;
            //}
            //else
            //{
            //   return false;
            //}

            return aux.Length == 11;
        }
    }
}

RsMotores.WEB/Controllers/CasaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RsMotores.WEB.Controllers
{
    public class CasaController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Titulo = "Index tipo string";
            ViewBag.Id = 1;
            ViewBag.Obj = new String("Oi");
            return View();
        }

        public IActionResult VerCasa()
        {
            ViewBag.Titulo = "Ver Casa"; //Recebe tipo de dados e relaciona seu tipo dinamicamente
            ViewData["Titulo"] = 10;
            
            return View();
        }
    }
}

RsMotores.WEB/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RsMotores.WEB.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RsMotores.WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        /*
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        */
        [HttpPost]
        public IActionResult Index(string email, string password)
        {
            ErrorMessage erroDados;
            var userDados = new Usuario()
            {
                cpf = "1232312312",
                email = "admin@admin",
                nome = "Admin",
                password = "123456"
            };

            ViewBag.Title = "Mensagem de Login";
            if (string.IsNullOrEmpty(email)&&
                string.IsNullOrEmpty(password))
            {
                erroDados = new ErrorMessage(3);
                ViewBag.Icon = "error";
                ViewBag.Msg= erroDados.msg;
                ViewBag.Color = "Red";
                return View("Error", erroDados);
            }
            else
            {
                if (email.Equals(userDados.email) && 
                    password.Equals(userDados.password))
                {
                    ViewBag.Icon = "sucess";
                    ViewBag.Msg = "Logado com sucesso";
                    ViewBag.Color = "Green";
                    return View(userDados);
                }
                else
                {
                    erroDados = new ErrorMessage(1);
                    ViewBag.Icon = "error";
                    ViewBag.Msg = erroDados.msg;
                    ViewBag.Color = "Red";
                    return View("Error", erroDados);
                }

            }
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RsMotores.WEB/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;



    namespace RsMotores.WEB.Controllers
{
    public class LoginController : Controller
{
    public IActionResult Token()
{
    ViewBag.Sistema = "RSMotores";
    return View();
}
}
}

RsMotores.WEB/Views/Casa/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>@ViewBag.Titulo</h1>

RsMotores.WEB/Views/Casa/VerCasa.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>@ViewBag.Titulo</h1>

RsMotores.WEB/Views/Home/Index.cshtml
@model RsMotores.WEB.Models.Usuario



<div class="text-center">
    <h1 style= "color:@ViewBag.Color">@ViewBag.Msg</h1>
    <p>Bem vindo @Model.nome</p>
    <a asp-controller="Login" asp-action="Token">Voltar ao início</a>
</div>
<script>
    Swal.fire({
        icon: '@ViewBag.Icon',
        title: '@ViewBag.Title',
        text: '@ViewBag.Msg'
    })
</script>

RsMotores.WEB/Views/Login/Token.cshtml
@{
    Layout = null;
}



@{
    
    //var sistema = "RS Motores";
    /*
    var dados = new string[] { "admin@admin", "senha" };
    */
}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Página de Login</title>
</head>
<body>
    <div class="container" id="container">
        <div class="form-container log-in-container">
            <form asp-controller="Home" asp-action="Index" method="post">
                <h1>Login</h1>
                <div class="social-container">
                    <a href="#" class="social"><i class="fa fa-google fa-2x"></i></a>
                    <a href="#" class="social"><i class="fa fa-instagram fa-2x"></i></a>
                    <a href="#" class="social"><i class="fa fa-facebook fa-2x"></i></a>
                    <a href="#" class="social"><i class="fab fa fa-github fa-2x"></i></a>
                </div>
                <span>ou digite seu usuário e senha</span>
                <input name="email" id="email" type="email" placeholder="Email" required />
                <input name="password" id="password" type="password" placeholder="Password" required />
                <a href="#">Esqueceu sua senha?</a>
                <button>Logar</button>
            </form>
        </div>
        <div class="overlay-container">
            <div class="overlay">
                <div class="overlay-panel overlay-right">
                    <h1>@ViewBag.Sistema</h1>



                </div>
                <img style="opacity:0.5; width:110%;" src="~/img/bg.png" />
            </div>
        </div>
    </div>
   
</body>
</html>

RsMotores.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RsMotores.WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <h1>
        RS Motores
    </h1>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RsMotores.WEB</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Casa" asp-action="Index">Casa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Casa" asp-action="VerCasa">Ver Casa</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RsMotores.WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>